### ISSUE TITLE
incompatible with kotlin version

### ISSUE THREAD

**Issue by nityanantan23** [mattermost/react-native-emm#11]
Hi how can i solvee this problem?

The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':mattermost_react-native-emm' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50

**Comment by enahum** [comment]
Have you set a `kotlinVersion` in your project build.gradle file?

**Comment by nityanantan23** [comment]
after adding the kotlin version in the latest react native, it produces this error

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not find any matches for com.facebook.react:react-native:+ as no versions of com.facebook.react:react-native are available.
     Required by:
         project :app
         project :app > project :mattermost_react-native-emm

**Comment by nityanantan23** [comment]
i solved the issue by adding `apply plugin: "com.facebook.react" ` to  `android/app/build.gradle`
`
