### ISSUE TITLE
possible to add root detection?

### ISSUE THREAD

**Issue by nityanantan23** [mattermost/react-native-emm#12]
Hi just a question, is it possible to add root detection in this library? so that it can natively support all the detections.

**Comment by enahum** [comment]
Hey @nityanantan23 you can use https://github.com/GantMan/jail-monkey in combination with this library, that is what we do ourselves

**Comment by nityanantan23** [comment]
hey @enahum, currently i am using that as well, but I noticed that it could be easily bypassed. so I thought of linking this [library ](https://github.com/byxiaorun/Ruru) with your emm, since its natively built. so it makes it hard to bypass it.

**Comment by enahum** [comment]
That library is only for Android, also jail-monkey do they checks natively

**Comment by nityanantan23** [comment]
I see, alright. Thank you for the info.
